changelog:
  exclude:
    labels:
      - documentation
    authors:
      - github-actions[bot]
  categories:
    - title: 🛠️ Breaking Changes
      labels:
        - breaking
    - title: ✨ Newly Added Features
      labels:
        - enhancement
    - title: 🩹 Essential Patches
      labels:
        - patch
    - title: Other Noteworthy Changes
      labels:
        - "*"
