name: PKG

on:
  pull_request:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install && cd workspace/mauss
      - run: ls -al
      - run: pnpm publish --dry-run --no-git-checks

      - uses: actions/upload-artifact@v3
        with:
          path: .
          retention-days: 5
