name: Release-CI

on:
  push:
    branches:
      - "master"

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '~ v')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install and publish
        run: npm install && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
